name: patch_map_flutter
description: "Utilities for applying JSON-style patch maps in Flutter apps."
version: 0.0.1
repository: https://github.com/conalog/patch-map-flutter
issue_tracker: https://github.com/conalog/patch-map-flutter/issues

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flame: ^1.35.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  json_path: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  dependency_validator: ^5.0.4
  pana: ^0.23.10
  cider: ^0.2.10

flutter:
  assets:
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700
